export let clubs = [
  "Driver",
  "Three Wood",
  "2 Iron",
  "4 Iron",
  "5 Iron",
  "6 Iron ",
  "7 Iron",
  "8 Iron",
  "9 Iron",
  "Pitching Wedge",
  "50 Degree",
  "54 Degree",
  "58 Degree",
];

export let course = {
  name: "Smoky Hill Country Club",
  Distance: "6146 yards",
  Slope: 126,
  Rating: 70.6,
  Holes: [
    { Name: 1, Par: 4, Distance: 391 },
    { Name: 2, Par: 5, Distance: 501 },
    { Name: 3, Par: 4, Distance: 327 },
    { Name: 4, Par: 3, Distance: 170 },
    { Name: 5, Par: 4, Distance: 431 },
    { Name: 6, Par: 5, Distance: 551 },
    { Name: 7, Par: 4, Distance: 315 },
    { Name: 8, Par: 3, Distance: 202 },
    { Name: 9, Par: 4, Distance: 392 },
    { Name: 10, Par: 4, Distance: 360 },
    { Name: 11, Par: 3, Distance: 169 },
    { Name: 12, Par: 4, Distance: 337 },
    { Name: 13, Par: 5, Distance: 515 },
    { Name: 14, Par: 4, Distance: 372 },
    { Name: 15, Par: 4, Distance: 352 },
    { Name: 16, Par: 4, Distance: 300 },
    { Name: 17, Par: 4, Distance: 316 },
    { Name: 18, Par: 3, Distance: 145 },
    ,
  ],
};

export let scores = [
  [
    {
      Par: 4,
      FIR: true,
      apprDistance: 122,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 234,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 60,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    {
      Par: 3,
      GIR: true,
      numberOfPutts: 1,
      Score: 2,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 154,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 272,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 45,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: false,
      apprDistance: 140,
      GIR: false,
      numberOfPutts: 3,
      Score: 5,
    },

    {
      Par: 4,
      FIR: false,
      apprDistance: 100,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    { Par: 3, GIR: true, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: true,
      apprDistance: 43,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 233,
      GIR: false,
      numberOfPutts: 1,
      Score: 5,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 89,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 113,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 63,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 78,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    { Par: 3, GIR: false, numberOfPutts: 1, Score: 3 },
  ],
  [
    {
      Par: 4,
      FIR: false,
      apprDistance: 99,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 255,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 43,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: true,
      apprDistance: 176,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 283,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 98,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: true,
      apprDistance: 121,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },

    {
      Par: 4,
      FIR: false,
      apprDistance: 134,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 4 },
    {
      Par: 4,
      FIR: false,
      apprDistance: 67,
      GIR: true,
      numberOfPutts: 3,
      Score: 5,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 267,
      GIR: true,
      numberOfPutts: 1,
      Score: 4,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 129,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 45,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 22,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 117,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    { Par: 3, GIR: false, numberOfPutts: 1, Score: 3 },
  ],
  [
    {
      Par: 4,
      FIR: false,
      apprDistance: 88,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 228,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 60,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    { Par: 3, GIR: true, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: true,
      apprDistance: 174,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 278,
      GIR: false,
      numberOfPutts: 2,
      Score: 6,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 39,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: true,
      apprDistance: 101,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },

    {
      Par: 4,
      FIR: false,
      apprDistance: 77,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    { Par: 3, GIR: true, numberOfPutts: 2, Score: 3 },
    {
      Par: 4,
      FIR: false,
      apprDistance: 87,
      GIR: false,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 5,
      FIR: true,
      apprDistance: 212,
      GIR: true,
      numberOfPutts: 2,
      Score: 5,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 65,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    {
      Par: 4,
      FIR: true,
      apprDistance: 65,
      GIR: true,
      numberOfPutts: 2,
      Score: 4,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 31,
      GIR: false,
      numberOfPutts: 1,
      Score: 4,
    },
    {
      Par: 4,
      FIR: false,
      apprDistance: 64,
      GIR: true,
      numberOfPutts: 1,
      Score: 3,
    },
    { Par: 3, GIR: false, numberOfPutts: 2, Score: 4 },
  ],
];

export let user = {
  username: "HoganBerens",
  password: "Pass123",
  handicap: "10",
  email: "hoganmberens@gmail.com",
  clubs: clubs,
  scores: scores,
};
